version: 2
before:
  hooks:
  - go mod download
builds:
-
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - "386"
    - amd64
    - arm
    - arm64
archives:
  -
    files:
    - COPYRIGHT
    - LICENSE
    - README.md
    - public/*
    format_overrides:
    - goos: windows
      formats: [zip]
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
-
  image_templates:
  - 'dunglas/uri-template-tester:{{ .Tag }}'
  - 'dunglas/uri-template-tester:v{{ .Major }}'
  - 'dunglas/uri-template-tester:v{{ .Major }}.{{ .Minor }}'
  - 'dunglas/uri-template-tester:latest'
  extra_files:
  - public/
