name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v5
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
    - name: Lint Helm Chart
      run: helm lint chart/uri-template-tester
